---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git ( sudo apt-get install git)
    apt:
      name: git
      state: present

  - name: i want to install tree
    apt:
      name: tree
      state: present

  - name: i want to instll wget
    apt:
      name: wget
      state: present
    