---
- hosts: 172.31.19.71
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: copy file into node side
    copy:
      src: mystaticfile
      dest: /home/maha/mystaticfile
  - name: i want to install webserver 
    apt:
     name: apache2 
     state: present
 
  - name: copy my index file into node side
    template:
       src: myindex.j2
       dest:  /var/www/html/index.html
    notify: restartwebserver

  handlers:
  - name: restartwebserver 
    service:
        name: apache2
        state: restarted


  

    