---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 webserver on ansible ubuntu nodes  (apt-get install apache2) 
    apt:
       name: apache2
       state: present

  - name: i want to start my apache2 webserver on  ansible ubtuntu nodes (service apache2 start)
    service:
       name: apache2
       state: started


       

